### ISSUE TITLE
Switcher/Login prompt corners look seriously ugly. Hardcoded icons, fonts.

### ISSUE THREAD

**Issue by nstommel** [linuxmint/slick-greeter#100]
```
 * slick-greeter version - current, this is somewhat irrelevant.
 * Distribution - Ubuntu Budgie 17.10
 * Graphics hardware - Intel HD630
 * 64 bit
 ```
**Issue**
On a standard, 1080p monitor, the corners of the prompt look ugly as sin. Please...fix this. Or allow themes for the box itself. 

**Steps to reproduce**
Logout, bootup to screen.  Just look at the rounded corners on the prompt box....ew. The Unity7 lightdm greeter never had these extremely unpleasant-looking corners. This greeter certainly does not look slick. The hardcoded fonts, pieces of gtk themes, icons, etc. are an extremely poor design choice.

**Expected behaviour**
See a nice rounded (or not rounded following gtk themes like Adapta would be ideal) transparent login dialog. No jagged round corners or abuse of .png files. (Please use svgs, seriously.) I can't even edit whatever pngs determine how the prompt is drawn, because presumably the svgs were created a long time ago, which don't currently exist (perhaps they once did, I don't know). 

**Other information**
Hardcoded fonts, hardcoded icons, the whole lot. This is seriously not an improvement. Allow for customization. Also...the clock time format is hardcoded in as well. It's maddening. There are several open issues about slick-greeter not even honoring critical settings.

**Comment by clefebvre** [comment]
http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
