### ISSUE TITLE
transparent input field

### ISSUE THREAD

**Issue by eoli3n** [linuxmint/slick-greeter#101]
```
 * Slick-greeter version : 1.1.4-1
 * Distribution - Ubuntu 18.04 daylibuild
 * 64 bit
 ```

**Issue**
Switch from unity greeter, and want it to look same
Input field has white backgroud

``Unity Greeter``
![yolo](https://ptpb.pw/Qu0L.png)

``Slick Greeter``
![yolo](https://ptpb.pw/OwXC.png)

Another thing is that i can't find ``Ubuntu 1X.04 LTS`` file path to try to use it as ``logo`` option, any idea ?

**Steps to reproduce**
Here is my conf file

```
[Greeter]
background=/usr/share/backgrounds/slick.jpg
draw-user-backgrounds=false
draw-grid=false
show-keyboard=false
show-hostname=true
show-power=true
show-clock=true
show-quit=true
activate-numlock=true
#logo=???
```

**Expected behaviour**

Transparent input field

**Comment by fossfreedom** [comment]
That field can be styled via your GTK theme

By default slick-greeter uses "Adwaita" (look in /usr/share/glib-2.0/schemas/x.dm.slick-greeter.gschema.xml)

So you can override theme-name and replace it with (for example) "Ambiance" if you have the light-themes packages installed.

If you do you'll see that the theme becomes transparent.  There is a unity-greeter.css file in the Ambiance theme that controls the theming for the greeter that works with slick-greeter as well.

**Comment by eoli3n** [comment]
Cool, works, thx <3
