### ISSUE TITLE
Feature request: allow setting cursor

### ISSUE THREAD

**Issue by ampetrosillo** [linuxmint/slick-greeter#106]
I think it would be useful if the cursor could be switched, as far as I can tell there is already some code devoted to setting a cursor:

https://github.com/linuxmint/slick-greeter/blob/ca56593b657225b295945fbaf96fee86966296c3/src/slick-greeter.vala#L618

A `cursor-theme-name` (and maybe `cursor-theme-size`) setting could be added, like the one there is for icons and themes.

**Comment by JosephMcc** [comment]
That's because your setting is specific for the user. You aren't a specific user on the greeter.

**Comment by CottonEaster** [comment]
Ah. Makes sense.

In that case, how about an option within the greeter's settings window for a mouse theme? That window has other theme options, already.

**Comment by iKarith** [comment]
Being able to set the cursor theme and cursor size are accessibility features FWIW, features added to lightdm-gtk-greeter in at least NixOS (NixOS/nixpkgs#25974). Don't know if the patch has migrated upstream or not. If I were a bit less lost looking at Vala source code, I'd be contributing a patch—I'm legally blind and I lose my mouse cursor easily on a 27" monitor. On a 14" laptop screen, I basically need to set it to 64 (not 48, which is the usual max offered) and _still_ tend to want a "locate cursor" hotkey.

Even not having any background in Vala, if someone who does offers me a couple of relevant pointers (it'd go here, that over there would do the kind of thing you'd want, etc.) I'd do the homework, get it working, offer the patch, and hope you'll use it in 20.1… I like improving accessibility, especially when it's accessibility for me! 😉

**Comment by knghtbrd** [comment]
Yeup, that will do what is desired! It's not in Debian yet to test it yet, but I think this issue can be safely resolved with 1.6.0. Should that be done, or should it be held off a couple weeks for the new version to propagate?
