### ISSUE TITLE
Login screen uses mirrored displays instead of extended displays

### ISSUE THREAD

**Issue by Strum355** [linuxmint/slick-greeter#110]
```
 * slick-greeter version 1.2.2
 * Distribution - Mint 19
 * Graphics hardware *and* driver used - i5 with intel hd, nvidia gt940m, nvidia driver 390
 * 64 bit
 ```

**Issue**

Login screen is present on all 3 monitors, 2 external + built-in laptop monitor. Background image is scaled incorrectly on the external monitors (possibly due to being a higher resolution?).
The displays appear to be mirrored as the mouse is present in all 3

**Steps to reproduce**

Fresh Mint 19 install.
Plug external monitors into laptop
Dont touch settings
Have nvidia gpu be active

**Expected behaviour**

Login text field is only present on one monitor/the displays arent mirrored

**Comment by moore-bryan** [comment]
This still persists on Solus 4.0.

**Comment by icarter09** [comment]
@Strum355  are you still experiencing this issue?

**Comment by Strum355** [comment]
Don't have the means to test this due to being "OoO"

**Comment by AdrianTwo** [comment]
Still occurs on Linux Mint 19.3 and slick-greeter 1.3.2 (1920x1200 and 1920x1080 display)

**Comment by AdrianTwo** [comment]
This is what it looks like:
![index](https://user-images.githubusercontent.com/53347802/85231771-388a3900-b3fa-11ea-8b97-4b3141d705ec.jpeg)

**Comment by AdrianTwo** [comment]
After reinstalling Linux Mint the problem went away.
