### ISSUE TITLE
Does not show wallpaper if using KDE Plasma 5

### ISSUE THREAD

**Issue by null-von-sushi** [linuxmint/slick-greeter#111]
```
 * slick-greeter version (1.2.1)
 * Distribution - Antergos (Arch based)
 * Intel HD Graphics ( 3rd Gen Core processor Graphics Controller [8086:166]), i915 driver (?)
 * 64 bit
 ```

**Issue**
Slick Greeter does not show the user's wallpaper if using KDE Plasma 5. 
I guess this is because the `/var/lib/AccountsService/users/my-username` file is never updated? 

**Steps to reproduce**
enable lightdm, configure it to use slick-greeter and log into a KDE Plasma session and change your desktop.

**Expected behaviour**
The greeter should show the wallapaper of KDE.

**Other information**
I did have some entry in the file, presumably from some other DE I was using in the past.

As a workaround I changed it by hand since I don't change my wallpaper *that* often.

References to AccountService I found online seem to be pretty old, is this still used? Is it possible to somehow manually update the record to show the current wallpaper?

**Comment by leigh123linux** [comment]
Is liblightdm-qt5 installed?

**Comment by null-von-sushi** [comment]
It was not. I installed it and rebooted, however the problem persists.

**Comment by clefebvre** [comment]
This should be a bug on Plasma itself. It should set AccountService when you change the background within the DE.
