### ISSUE TITLE
touchpad: tapping is disabled

### ISSUE THREAD

**Issue by rdecleen** [linuxmint/slick-greeter#112]
```
 * slick-greeter version (slick-greeter --version)
Kernel: 4.15.0-30-generic x86_64 bits: 64
Desktop: Cinnamon 3.8.8
Distro: Linux Mint 19 Tara
Asus Zenbook UX430UA
 ```

**Issue**
Accesibility & Quit button on login screen (without being logged in) not working
Mint 18.3 Cinnamon > click button "Quit" shows options supend / hibernate / quit
Mint 19 Cinnamon   > click button "Quit" does nothing (shows only tooltip)

**Steps to reproduce**
Before logging in, try clicking on Accessibility or Quit

**Expected behaviour**
showing suspend/hibvernate/quit dropdown oprions

**Other information**

**Comment by rdecleen** [comment]
additional info: used linuxmint-19-cinnamon-64bit-v2.iso

**Comment by rdecleen** [comment]
decided to attach a Logitech mouse to the laptop instead of using the built-in touchpad.
Guess what? Buttons function perfectly!
So yes, it is hardware related, seems the Touchpad in the Asus Zenbook UX430UA-GV002T does not want to play nice with those buttons.
With a proper mouse attached no issues at all...

**Comment by rdecleen** [comment]
for all other purposes the touchpad works and clicks away just fine, just not on the buttons on that login screen... Even funnier than that: using the right click (on the touchpad) makes the buttons behave as they should, working fine. But using double-tap on the touchpad itself gives the result described, just the tooltip text.

**Comment by gm10** [comment]
With the above we've narrowed it down to the user expecting to have tap-to-click working on the login screen when it isn't. So while this is not a bug, it should probably be taken as a feature request, probably best for `lightdm-settings` to add a toggle for this to the input options. See also my post here:
https://forums.linuxmint.com/viewtopic.php?p=1512113#p1512113

**Comment by clefebvre** [comment]
Hmm, I'm not sure we want to configure Xorg. I mean that's a much bigger scope for lightm-settings than what it currently handles..

**Comment by gm10** [comment]
> Hmm, I'm not sure we want to configure Xorg. I mean that's a much bigger scope for lightm-settings than what it currently handles..

Understandable. I have no stake in this, but as far as I recall the default in Windows is to have this enabled, so I am not surprised new users get confused by this. In view of this target audience, if you don't want to change the defaults maybe consider adding an optional, enabled by default info banner to the login screen when a touchpad is detected. I'd say add it to mintwelcome instead if I thought it would get read. ;) Just an idea.

**Comment by Vahan86** [comment]
> decided to attach a Logitech mouse to the laptop instead of using the built-in touchpad.
> Guess what? Buttons function perfectly!
> So yes, it is hardware related, seems the Touchpad in the Asus Zenbook UX430UA-GV002T does not want to play nice with those buttons.
> With a proper mouse attached no issues at all...

I have the same issue with Linux Mint 19.3, Cinnamon 4.4.8, slick-greeter 1.3.2
I have HP Envy laptop and by using built-in touchpad clicking doesn't work neither for choosing user, nor for using panel indicators. With external mouse everything works fine.

**Comment by Vahan86** [comment]
@icarter09, can we mark the issue as a bug?
