### ISSUE TITLE
Feature request (/bug report): disable the battery indicator

### ISSUE THREAD

**Issue by ghost** [linuxmint/slick-greeter#117]
```
 * slick-greeter version (slick-greeter --version)  1.2.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * Graphics hardware *and* driver used: NA
 * 32 or 64 bit: 64
 ```

**Issue**

My ThinkPad shows the battery icon - denoting charging - on the lock screen, even when the battery is charged fully in the sense of being charged to its threshhold. I imagine that the misreading owes to my charging threshold (or thresholds) not being at their default value; I changed the value via `tlp`. The system applet also shows 'charging' when it should not (as reported, by multiple persons, [here](https://github.com/linuxmint/Cinnamon/issues/6324)). Anyhow, a way around the problem would be allow the user to stop the greeter showing the charging status.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by clefebvre** [comment]
This configuration option is present in lightdm-settings.
