### ISSUE TITLE
Only users at that start of /etc/passwd are displayed

### ISSUE THREAD

**Issue by alkisg** [linuxmint/slick-greeter#118]
```
 * slick-greeter 1.1.4
 * Ubuntu MATE 18.04.1
 ```

My /etc/passwd has the following accounts:
 * system accounts
 * teacher1
 * 100 students
 * teacher2

In this scenario, teacher2 can't login as there's some hard limit on how many users slick-greeters **reads** from passwd **before** doing any hiding or matching.

So, if I create /etc/lightdm/slick-greeter.conf with the following contents:
[Greeter]
group-filter=teachers
hidden-users=user1 user2 ... user100

...then I only see "teacher1" in the greeter, because it never read the teacher2 account due to some hard limit.

A work around is to `nano /etc/passwd`, and move the teacher2 line above the 100 student lines. Then the greeter reads it and displays it properly.

I.e. please read all users; only impose hard limits on display **after** you do the filtering/hiding.

**Steps to reproduce:**
* Create 100 users: `for i in $(seq 100 199); do yes | adduser u$i; done`
* Then create an additional administrator user: `adduser addministrator2; gpasswd -a administrator2 sudo`
* Then try to login as administrator2, it's impossible even with group-filter=sudo in the configuration.

**Comment by alkisg** [comment]
Btw, it would be nice if you also respected the common variables of /etc/lightdm/*.conf, like hidden-users etc. It's strange that you require a specific file name there for common variables that should be shared between all greeters.

**Comment by leigh123linux** [comment]
Maybe you should update to a supported version, slick-greeter-1.2.2

**Comment by alkisg** [comment]
Hmm, it's sad if "the latest LTS Ubuntu version" doesn't have a "supported greeter".
Do you offer a PPA for Ubuntu?
Is it available in any distribution so that I could test there?

I'm guessing the problem will affect the latest version as well though.

**Comment by leigh123linux** [comment]
Have you considered switching to the latest Mint-19, that will have the latest slick-greeter.

**Comment by alkisg** [comment]
I tried on a Mint 19 VM and it has the issue too.
```
slick-greeter 1.2.2
Linux Mint 19 Tara
```

I also added an easy way to create 100 users in the issue description above, so that anyone can easily reproduce the issue in any distribution he prefers.

**Comment by alkisg** [comment]
I believe the problem is in accountsservice daemon.c => MAX_LOCAL_USERS 50.
I commented on the bug which caused that limit:
https://gitlab.freedesktop.org/accountsservice/accountsservice/issues/39#note_80893

**Comment by alkisg** [comment]
One workaround is to create /etc/lightdm/lightdm.conf.d/sch-scripts.conf with the following contents:
[SeatDefaults]
greeter-show-manual-login = true

Then the users need to type their name to login, but at least they can login.

I'm closing this issue, I don't think slick-greeter is responsible for accountsservice shortcomings. If accountsservice ever supports an API for applying "group-filter" BEFORE the MAX_LOCAL_USERS=50 limit, then slick-greeter can use that API, but that's just wishful thinking.
