### ISSUE TITLE
It is hard to leave the session-choice menu

### ISSUE THREAD

**Issue by ghost** [linuxmint/slick-greeter#119]
```
 * slick-greeter version (slick-greeter --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.3
 * Graphics hardware *and* driver used: 3.0 Mesa 18.0.5; Intel UHD Kabylake 620
 * 32 or 64 bit: 64
 ```

**Issue**

It is hard to leave the session-choice menu.

**Steps to reproduce**

1) Boot. 
2) Click the little mountain icon (which lacks a tooltip, at least on system). A menu pops up. 
3) Try to leave the menu by clicking outside it or pressing escape. Fail to leave the menu. To leave the menu, one must click the arrow icon to the left. This is confusing and that matters, especially because, often, people will start messing with different sessions when they are having some sort of trouble already. Moreover, fixing this infelicity would, I imagine, not be hard (though I lack the skills to do it myself). EDIT: also, tap-to-click doesn't work in the greeter (at least on my machine), so if you are having trouble logging on ('cos something has messed with your system) then that's _another_ thing that will worsen your experience. If the leaving-of-the-menu is improved then that's at least one less hassle.

**Expected behaviour**

It should be easy to leave the menu.

**Other information**

Mint 19.0 had the same problem.

Cf. #87 , which is a complaint about a scenario in which - inconsistent with the behaviour I report here - the greeter dispenses with arrows.

**Comment by Vahan86** [comment]
I have the same issue with Linux Mint 19.3, Cinnamon 4.4.8, slick-greeter 1.3.2.
There is also no way to select a working environment / session using keyboard, it is only possible with mouse.
