### ISSUE TITLE
If a script changes user background while the greeter is showing, does/can it redraw?

### ISSUE THREAD

**Issue by peterlevi** [linuxmint/slick-greeter#125]
```
 * slick-greeter 1.2.4
 * Distribution - Mint 19.1 Tessa XFCE
 * VM on standard laptop Intel videocard
 * 64 bit
 ```
I am tasked with writing a script that uses the wallpaper to display some external status information in a very prominent manner.
slick-greeter is set to display user backgrounds.
When it is initially shown, it does show the current background. However, as my script continues running in the background and changes the wallpaper while the greeter is shown, slick-greeter does not refresh the image - it remains the same as the one originally shown. Can it somehow be triggered to redraw it?  

Thanks a lot,
Peter

**Comment by icarter09** [comment]
@peterlevi were you able to resolve your issue?

**Comment by peterlevi** [comment]
@icarter09 Not as of the time I was last working on this (which was around the time I opened the issue).

**Comment by clefebvre** [comment]
It would need to monitor the file for changes. It's not a supported feature, there's no reason for it to do so.
