### ISSUE TITLE
Doesn't indicate change of keyboard layout

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/slick-greeter#135]
```
 * slick-greeter version - 1.2.4
 * Distribution - Alt Linux Sisyphus
 * 64 bit
 ```

**Issue**
It seems that slick greeter tries to support different keyboard layouts - there is slick-greeter-set-keyboard-layout script that reads /etc/default/keyboard and calls setxkbmap utility. But it means that you could also specify shortcut to change current layout - it is real use case if e.g. one user has english passphrase and another one uses Cyrillic. Moreover this shortcuts work but slick-greeter doesn't shows that layout was changed that could confuse the user.

**Steps to reproduce**
1. Specify 2 system layouts (e.g. us + ru) and specify keyboard shortcut to change layout
2. Reboot machine
3. On greeter screen change layout
4. Layout will be changed but greeter still shows old layout

**Expected behaviour**
Greeter should show active layout. Ideally it should allow to change layout using UI.

**Comment by luv** [comment]
**Moreover this shortcuts work but slick-greeter doesn't shows that layout was changed that could confuse the user.**

I can confirm this issue.

my /etc/default/keyboard:

`# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="us,cz"
XKBVARIANT=""
XKBOPTIONS="grp:alt_shift_toggle"

BACKSPACE="guess"
`

alt shift changes the layout but the keyboard indicator still shows "us"

**Comment by Vahan86** [comment]
I have the same issue with Linux Mint 19.3, Cinnamon 4.4.8.

I am not able even to change keyboard layout by set keyboard shortcuts. Shortcuts don't work at all.

**Comment by luv** [comment]
Did you manually edit /etc/default/keyboard (note XKBOPTIONS="grp:alt_shift_toggle") and the shortcuts still do not work?

Indeed this is an important issue that hopefully gets fixed soon.

**Comment by Vahan86** [comment]
@luv, I have edited /etc/default/keyboard and the shortcuts still don't work. 

@icarter09, can we mark this issue as a bug?

**Comment by jonathangold** [comment]
I have the same issue. My `grp:shifts_toggle` shortcut is working, but the layout indicator always shows whichever layout was set when it launches.
