### ISSUE TITLE
FTBFS with vala-0.45.3

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/slick-greeter#137]
```
 * slick-greeter version - slick-greeter-1.2.6
 * Distribution - Fedora 31 (Rawhide)
 * vala-0.45.3
 * 64 bit
 ```

**Issue**

slick-greeter fails to compile with vala-0.45.3

```
BUILDSTDERR: make[2]: Leaving directory '/builddir/build/BUILD/slick-greeter/greeter-list.vala:167.5-167.22: error: Creation method of abstract class cannot be public.
BUILDSTDERR:     public GreeterList (Background bg, MenuBar mb)
BUILDSTDERR:     ^^^^^^^^^^^^^^^^^^
BUILDSTDERR: make[2]: *** [Makefile:1106: slick_greeter_vala.stamp] Error 1
BUILDSTDERR: make[2]: *** Waiting for unfinished jobs...
```

**Steps to reproduce**

Try to compile slick-greeter with vala-0.45.3

**Expected behaviour**

slick-greeter should compile.

**Other information**

**Comment by leigh123linux** [comment]
Build.log

https://kojipkgs.fedoraproject.org//work/tasks/6193/36606193/build.log

**Comment by fossfreedom** [comment]
Changing the declaration from public to protected will resolve this as per https://gitlab.gnome.org/GNOME/vala/issues/766

Note - stable v0.46 of vala is due early Sept so things may change between now and then.
