### ISSUE TITLE
Long errors are not fully displayed

### ISSUE THREAD

**Issue by vdcow** [linuxmint/slick-greeter#146]
```
 * slick-greeter version - 1.3.0
 * Distribution - Alt Linux
 * 64 bit
 ```
**Issue**

Right now if error displayed by slick-greeter is too long it can't be fully displayed.  It introduces several problems:
1. User can't understand what happened because part of error message is missed. E.g. 
https://bugzilla.altlinux.org/attachment.cgi?id=8459
2. Some UI elements are not shown. E.g. if passphrase is expired then Russian error message is quite long and it causes part of the UI is not shown
https://bugzilla.altlinux.org/attachment.cgi?id=8462
https://bugzilla.altlinux.org/attachment.cgi?id=8461

**Steps to reproduce**
Change system language to Russian and trigger error with long message e.g. expired passphrase.

**Expected behaviour**
Error message is fully displayed, all UI elements are visible.

**Comment by icarter09** [comment]
@vladimir-didenko  are you still experiencing this issue?

**Comment by vladimir-didenko** [comment]
@icarter09 Yes issue still exists

**Comment by icarter09** [comment]
@vladimir-didenko thanks for the update.

**Comment by scottdmilner** [comment]
Hi, is there an update on this issue? This can be frustrating for users trying to change their password, as when as password is rejected for some reason, the rejection reason is not displayed. Thanks!
