### ISSUE TITLE
User background not loaded if added from "Gnome Settings > Add Picture"

### ISSUE THREAD

**Issue by algent-al** [linuxmint/slick-greeter#160]
```
 * slick-greeter 1.4.0
 * Distribution - (Solus Budgie)
 * 64 bit
 ```

**Issue**
User background not loaded in login screen if user background was set through Gnome settings using "Add Picture".
Instead it is loaded login screen background.
![background](https://user-images.githubusercontent.com/46356616/82708537-c4d00180-9c7e-11ea-9b7f-d570b4d5d979.png)
The three icons with a close button was set by this way and they were saved to `~/.local/share/backgrounds`. Every background at this location have this issue.

**Steps to reproduce**
1. Enable "Draw User Backgrounds" on `lightdm-settings` or edit `/etc/lightdm/slick-greeter.conf` by adding a new line `draw-user-backgrounds=true`.
2. Gnome Settings > Background > Add Picture.
Then choose the desired wallpaper.
3. Log out, switch users and check if the user background is displayed.

**Expected behaviour**
Log out and then switch users. For each users should be displayed the chosen background from Gnome Settings.

**Comment by clefebvre** [comment]
We get the background from LightDM, which itself gets it from AccountService.

This should be reported against Gnome Settings directly. If they argue that background support isn't a formal part of AccountService (it was patched by Ubuntu last time I checked), then this should be a bug reported to Ubuntu instead.
