### ISSUE TITLE
missing seperator error when running make

### ISSUE THREAD

**Issue by skittlesvampir** [linuxmint/slick-greeter#162]
```
 * version 1.4.0
 * Distribution - Void Linux
 * 64 bit
 ```

**Issue**
I ran `./autogen.sh` and everything was successful.
After that I ran `make` and it told me that there is a  missing seperator in line 640.
Have I done something wrong or is it something with the makefile?

**Comment by icarter09** [comment]
I'm not able to reproduce this issue. Slick-greeter was compiled successful when running `make`.

**Comment by ndgnuh** [comment]
I can reproduce this one with xbps-src, here's the template file 

```shell
# Template file for 'lightdm-slick-greeter'
pkgname=lightdm-slick-greeter
version=1.5.2
revision=1
#archs="i686 x86_64"
wrksrc=slick-greeter-${version}
#create_wrksrc=yes
build_style=gnu-configure
make_build_target="install"
configure_script="./autogen.sh"
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends="intltool pkg-config gnome-common which"
makedepends="cairo-devel freetype-devel libcanberra-devel gettext-devel lightdm-devel libxklavier-devel vala at-spi2-core gtk+3-devel"
depends="pixman cairo freetype lightdm liblightdm-gobject gtk+3 libXext"
short_desc="A slick-looking LightDM greeter"
maintainer="ndgnuh <ndgnuh@protonmail.com>"
license="GPL-3.0"
homepage="https://github.com/linuxmint/slick-greeter"
distfiles="https://github.com/linuxmint/slick-greeter/archive/${version}.tar.gz"
checksum=4462d82d79b483e5f2cb3ef52078b2d60056f2db5e7806b0e3fd44d2685e23b2
```

Makefile line 635-645:
```makefile
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
```

**Comment by mtwebster** [comment]
Which folder is this makefile in? There are a number of them in different folders.  These are auto-generated, not meant to be edited - it's possible there's some issue in the file's associated Makefile.am that causes this - this is usually the case, though I'm not sure why you're the only ones experiencing this.

**Comment by ndgnuh** [comment]
@mtwebster This is the `Makefile` at the top level of the source directory, somehow the PKGBUILD in [aur](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lightdm-slick-greeter) works but this doesn't...

**Comment by ndgnuh** [comment]
Nvm everyone, I've found the culprit. I was missing dependencies like `vala-devel glib-devel`. Adding those to `hostmakedepends` will do the job. 

Turns out someone did build this successfully (https://github.com/void-linux/void-packages/pull/24933/files). I don't know how they figured out that some dependencies were missed though.

**Comment by skittlesvampir** [comment]
I think I should close this issue.
