### ISSUE TITLE
Slick greeter doesn't show "session" icon

### ISSUE THREAD

**Issue by pahhur** [linuxmint/slick-greeter#167]
Kernel 5.4.0-42-generic
Slick greeter 1.4.1
OS Mint XFCE 20.04, 64 bit
Graphics driver Nouveau

**Issue**
After upgrade (new install) to Mint 20.04, slick-greeter was installed and used instead of ligthdm-gtk-greeter.
A standard xfce.desktop was created in SESSIONS=/usr/share/xsessions/, and is working perfectly.
The "session" icon is not displayed on the login screen, as there are no more sessions listed in $SESSIONS
So far, so good.

However, this remains true, even when I add another .desktop file (0644) to $SESSIONS
and since there is no button, only XFCE can be started.
lightdm-settings does not give me an option to enable more sessions (aka window managers) neither.

Since I see that icon on the slick-greeter pictures: What do I have to do to enable it and get the previous behaviour?

**Steps to reproduce**
Fresh install Mint 20.04 XFCE
add a .desktop file to $SESSION 
restart system or lightdm

**Expected behaviour**
slick-greeter should show a session icon, and on click on that, an entry for every .desktop file in $SESSION

**Other information**

**Comment by pahhur** [comment]
Mea culpa. A [ was missing in the desktop file

**Comment by cwhuang** [comment]
I have exact the same issue. Slick-greeter can't show the icon of my custom xsession on the login screen.
Could you explain why the issue is closed? What's the correct way to add icon for my xsession?
Thanks!
