### ISSUE TITLE
Cannot change keyboard layout in login screen

### ISSUE THREAD

**Issue by juliuspopp** [linuxmint/slick-greeter#173]
```
 * Cinnamon version 4.6.7, slick-greeter 1.4.1
 * Distribution - Mint 20.0
 * Graphics hardware *and* driver used: intel integrated graphics
 * 64 bit
 ```

**Issue**
Cannot change keyboard layout in login screen.
The layout is shown in the top right corner, but no drop down menu opens when clicking on it.

**Steps to reproduce**
during installation select "German" as default layout.
Add new layout "German (Neo 2)".
Try to log in using the new layout. 

**Expected behaviour**
When clicking on the icon in the top right corner, a menu should open allowing to switch keyboard layouts.
EDIT: Ideally the default layout of the user would be selected automatically and all other layouts of that user and the default layout are easily accessible.

**Other information**
1920x1080. 
User was on auto login when the new layout was added.

Same / similar issue:
https://github.com/linuxmint/cinnamon/issues/3048
https://github.com/linuxmint/cinnamon/issues/3483
https://github.com/linuxmint/cinnamon/issues/3803

**Comment by bartaszili** [comment]
I can confirm as well. Mint 20.1 64bit Cinnamon. During installation default keyboard layout was HU on laptop. But I'm using a wireless US int. (Logitech 295) keyboard on a daily basis instead. Tried to manually add both layouts to /etc/default/keyboard with no luck. Can't change. Sits on the first declared.

**Comment by sebastianradakovits** [comment]
I too have this problem.

**Comment by gordongw** [comment]
I can confirm I am experiencing the same issue.

**Comment by justafreaky** [comment]
Same issue. Can't switch to Russian.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/slick-greeter/commit/1aa6d5888df372c677cbc06a770e7ab2e4f0c8b6.

The greeter will now list all lightdm layouts, and give easy access to layouts specified in /etc/default/keyboard.
