### ISSUE TITLE
No option for guest session

### ISSUE THREAD

**Issue by SamBurgos** [linuxmint/slick-greeter#18]
Greetings, I was looking into this particular issue, but I don't know neither I am sure if the problem lies here or on lightdm, I was able to compile and create a package of slick-greeter on Archlinux, but no matter what, I don't have an option available to enable a guest session

![virtualbox_arch devel_19_04_2017_12_06_02](https://cloud.githubusercontent.com/assets/1509924/25194768/b6fba024-24f8-11e7-94fc-47fb19ef926d.png)

You can see on the screenshot that I manage to compile it and works properly (I think, correct me if I am wrong), but I don't have the option to enter into a guest session. Once again, probably there is something I may be missing but I leave some options down here related to the compiling process:

* This is the packaging I took as a base for the compilation, these are the options available from unity-greeter on Arch: [unity-greeter compilation options](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lightdm-unity-greeter)

* This is the packaging of slick-greeter, you can check and maybe [compare some options here](https://github.com/SamBurgos/Sam-PKGBUILD/blob/master/PKGBUILD-lightdm-slick-greeter). _As an off-topic, that repository also has the lightdm-settings packaging and some other packages as well_

After some testing I manage to remove the patching options and it compiles and works successfully, except from some warnings that I took some screenshot (_I do owe you those since the computer I am using right now doesn't have those screenshots, but maybe I can try to attach them once I get home_); but if you can help me checking I will appreciate it

**Comment by SamBurgos** [comment]
Sorry it took long, I have been arriving quite tired to my home and some things on my laptop are a disaster, here are the promised screenshots:

![virtualbox_arch dev_17_04_2017_08_11_17](https://cloud.githubusercontent.com/assets/1509924/25281252/fcceb77c-2669-11e7-9485-4b9db73c1ce7.png)

![virtualbox_arch dev_17_04_2017_08_11_32](https://cloud.githubusercontent.com/assets/1509924/25281251/fcc951c4-2669-11e7-81e7-277dc948bca4.png)

As far as I understand (correct me if I am wrong), these are not error in the compilation but more like warnings about deprecated stuffs (Linux Mint GTK is 3.18, Arch Linux GTK is 3.22 at the moment of writing this), but there are some GLib.Error that I don't know if it is the greeter looking for some things, or the lightdm settings that are not available at the moment. I tried to change and manually enable the greeter-allow-guest and allow-guest manually on the lightdm.conf but is not giving me any option to enable the guest session.

Hope this can help you

**Comment by clefebvre** [comment]
Hi Sam,

I think it's a configuration issue on your side. I can't be 100% sure, but I can confirm guest session working fine here.

**Comment by SamBurgos** [comment]
I see, is there any chance that I can enable some kind of early access to Linux Mint 18.2 to check that? I do have a VM that I do not mind using as a testing area and break things if necessary so I can check configuration or if there is any package, patch or anything that allows lightdm on Ubuntu/Mint to enable guest session and maybe try to replicate that on my Arch installation

**Comment by Ste74** [comment]
I think is not a problem of the greeter.. you can with other greeter create a guest option ? The guest option is a particular user if this user not exist in the system the greeter not found.. any arch system with lightdm as dm i think don't have this ...

**Comment by SamBurgos** [comment]
@Ste74 I see, I have been looking on any package, configuration, patch or anything that should allow to create any guest session, but so far I have found only [this one](https://aur.archlinux.org/packages/guest-account/) and this [other one](https://aur.archlinux.org/packages/systemd-guest-user/). On my work I only have an Arch (Antergos to be more specific) VM available, but at home I have Antergos and Mint installed, and I would like to check the approach of Ubuntu on handling those kind of sessions, be it patch, package, or any configuration file on lightdm or the greeter

**Comment by SamBurgos** [comment]
Well, at the end, it seems that we can blame Ubuntu (¬_¬) for just enabling guest session on that distro and derivatives, after a while of looking and digging I get to the conclusion that Ubuntu does something at compilation time so that they can not only enable guest session, but also there is a sh file that somehow allows it to enable that guest session, some screenshots to prove that:

![slick greeter_arch devel](https://cloud.githubusercontent.com/assets/1509924/26029356/513bf670-37f0-11e7-8030-ea39b00e3d5d.png)

![slick greeter_mint](https://cloud.githubusercontent.com/assets/1509924/26029357/544d47ec-37f0-11e7-9516-5abc4f08b82e.png)

![lightdm_guest account 1](https://cloud.githubusercontent.com/assets/1509924/26029358/5a61a3bc-37f0-11e7-83fb-fe08a96f5b1f.png)

![lightdm_guest account 2](https://cloud.githubusercontent.com/assets/1509924/26029359/5e9c2c4a-37f0-11e7-915d-c3fbd4e45112.png)

Though is not really fair (once again I do blame Ubuntu on a politely way), I guess that on other distros we need to look on a way to enable that guest session, since Arch (and Manjaro/Antergos as well @Ste74 ) always uses it the vanilla approach on all of their packages as well, and probably that is why guest session is never enabled on Arch/Manjaro/Antergos

If you don't mind @clefebvre I will close this since the problem is not on slick-greeter but on lightdm itself
