### ISSUE TITLE
Slick-greeter may be responsible for icon positions not being restored in xfce desktop session

### ISSUE THREAD

**Issue by morciej** [linuxmint/slick-greeter#180]
```
 * slick-greeter version (1.5.2+ulyssa)
 * Distribution - (Mint 20.1) / XFCE
 * Graphics hardware *and* driver used - Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
           vendor: Acer Incorporated ALI driver: i915 v: kernel bus ID: 00:02.0 chip ID: xxxx:xxxx 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 2000 (SNB GT1) v: 3.3 Mesa 20.2.6 
           compat-v: 3.0 direct render: Yes
 * 64 bit
 ```

**Issue** Icons are rearranged on desktop every startup

**Steps to reproduce** Arrange or auto-arrange icons on desktop, then (possibly after a short delay) restart the machine.

**Expected behaviour** Icon positions are correctly restored (as long as it is a one-monitor system with the same screen resolution as before)

**Other information** A comment on xfce forum ([https://forum.xfce.org/viewtopic.php?pid=41768#p41768](https://forum.xfce.org/viewtopic.php?pid=41768#p41768) suggests that [a] greeter might be responsible, by changing screen resolution during startup. The possible behaviour is that xfce session is seeing the change of resolution during startup as a reason to regard saved icon positions as invalid, and arranges them randomly.

**Comment by leigh123linux** [comment]
File the issue against XFCE.

**Comment by morciej** [comment]
I already did. I am not sure who is better positioned to solve it.

**Comment by leigh123linux** [comment]
lightdm/slick will use the default system resolution. if it's set differently in xfce session they need to handle the change.
You could hack lightdm resolutioln, see https://gist.github.com/levlozhkin/545c0ebc69e551ef92b4#file-kms-lightdm-xfce-resolution-match-sh-L23

**Comment by morciej** [comment]
Thanks. I don't think I want to hack anything, just to solve a long-standing issue that arises somewhere on the interface between Mint and XFCE. The resolution does not actually change. It is the presence of the panel that forces the change of _nominal_ width of the screen. In any case, I will continue to ask XFCE to fix this on their end.
