### ISSUE TITLE
Feature request: an option to reboot to recovery

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/slick-greeter#182]
On Mint is can be fiddly to get into the recovery environment. One has to mess around with hitting shift or escape or fiddle with grub settings. So, in pursuit of user-friendliness (and greater 'slickness'), why not add a boot-to-recovery option to the greeter?

**Comment by clefebvre** [comment]
Does LightDM support such a feature?

**Comment by LinuxOnTheDesktop** [comment]
@clefebvre : if you are asking me, then I am afraid that I must reply that I do not know!

**Comment by clefebvre** [comment]
Ok I'll close this for now. I'm not against the idea but I'm not sure if it's feasible nor if this would be the best place to expose such functionality.

I agree that showing the hidden boot menu is tedious though and doesn't reliably work.
