### ISSUE TITLE
No login screen 

### ISSUE THREAD

**Issue by MahmoudZaher0** [linuxmint/slick-greeter#183]
```
 * Cinnamon version (20 Ulyana)
 * Distribution  (Mint 20 Ulyana) 
 * Nvidia GeForce MX230 *and* Intel Iris plus Graphics G7
 * Kernel: 5.4.0-70-generic
 * x86_ 64 bit
 ```

**Issue**
After turning on the machine and choose to boot to mint Cinnamon ( dual boot user) login screen don't appear just dell logo and cursor.

**Other information**
This happened while I Was editing some config files for KDE plasma and other files  has deleted.

**Comment by leigh123linux** [comment]
> > @MahmoudZaher0 what config files were you editing?
> 
> KDE plasma 5. I was deleting some Configurations for a bunch of extentions comes with KDE plasma.

Try using mint forum as I don't consider PICNIC as a bug.

**Comment by clefebvre** [comment]
hi @MahmoudZaher0 I'm closing this report since there's no identified bug.

Note: You can use timeshift to restore deleted files and get back to a working system.
