### ISSUE TITLE
Configuration not read from /etc/lightdm/lightdm.conf.d/*.conf

### ISSUE THREAD

**Issue by DaAwesomeP** [linuxmint/slick-greeter#189]
```
 * slick-greeter version 1.2.4-2
 * Distribution - Rasperry Pi OS Lite (Debian Buster)
 * Rapsberry Pi 4
 * armhf
 ```

**Issue**
Additional configuration not read from `/etc/lightdm/lightdm.conf.d/*.conf`.

**Steps to reproduce**
Create a conf file in `/etc/lightdm/lightdm.conf.d/` with a `[Greeter]` section. Slick Greeter will not read or configure itself from this file.

**Expected behaviour**
As with the rest of LightDM, a `[Greeter]` section in a conf file found in  `/etc/lightdm/lightdm.conf.d/` should be read in alphanumerical order by filename.

**Other information**
Maybe this is specifically a Debian package implementation issue and not an issue with Slick Greeter. Please let me know and I will close this issue.

**Comment by clefebvre** [comment]
This was never supported afaik.
