### ISSUE TITLE
Feature request: Add IP indicator on slick-greeter

### ISSUE THREAD

**Issue by slegjunk** [linuxmint/slick-greeter#190]
```
 * slick-greeter version - 1.4.1
 * Distribution - Linux Mint 20 Ulyana
 * Graphics hardware *and* driver used - Intel\i915
 * 64 bit
 ```

Greetings. We, among the workplace support department, actively use your greeter in our company with Cinnamon 20.04. Everything would be fine, but one very important detail for us is missing - no display of the ip address on the login screen panel. We kindly ask you to add this applet or feature.  Thanks a lot for your jobs!

**Comment by clefebvre** [comment]
Hi @slegjunk, it shows the hostname though... that can be used as a unique machine identifier.

This isn't easy because there's no concept of a single IP address per machine. You might have many, you might have none, you might route here or there based on packet destinations...
