### ISSUE TITLE
"Invalid session" on Wayland sessions

### ISSUE THREAD

**Issue by SethBarberee** [linuxmint/slick-greeter#195]
```
 * slick-greeter version: 1.5.4-1
 * Distribution - Arch
 * AMD RX Vega 56 / mesa 21.2.4-1
 * 64 Bit
 ```

**Issue**

On any wayland session, the log will have 
`slick-greeter.vala:218: Invalid session: ...`

slick-greeter is coded to only validate xsessions. Since LightDM supports launching Wayland sessions too, this should probably be removed or fixed. Wayland sessions are stored in `/usr/share/wayland-sessions`.

https://github.com/linuxmint/slick-greeter/blob/99d04416a2aa8e56df919e5b148030b0ef30f7a9/src/slick-greeter.vala#L216

**Steps to reproduce**
Choose any wayland session.

**Expected behaviour**
Message shouldn't be printed as it's a vallid session file in `/usr/share/wayland-sessions`

**Comment by clefebvre** [comment]
This is fixed in master.
