### ISSUE TITLE
Cannot change login user in greeter

### ISSUE THREAD

**Issue by gitatr** [linuxmint/slick-greeter#196]
```
 * slick-greeter version 1.5.4
 * Distribution - (Mint 20.2
 * Graphics hardware *and* driver used - std intel i7-11thgen
 * 64 bit
 ```

**Issue**
Using the default settings, one cannot choose to login with any other user than what slick-greeter offers. When a new user is created, slick-greeter switches to that user as a default. Only some obscure setting about "Allow manual login" - for whatever this means - allows one to enter a user name, which at least is hinted at in the tooltip.

**Steps to reproduce**
1. Install Linux Mint.
1. Add another user after the installation using the gui. e.g `user2`
1. `slick-greeter` offers no way to choose a different user than `user2`

**Expected behaviour**
* Slick greeter remembers the last user we used to log in
* Some way is offered to choose, or at least enter, a different user name
* Which user was created last, has no bearing on what slick-greeter offers as a default for "auto-" login

**Other information**

**Comment by gitatr** [comment]
I even forgot:
Steps to reproduce:
4. Log back in with user2
5. Choose Log-Out -> "Switch user"
6. Only `user2` is available for login

## Expected behaviour:
* at least via Log-Out -> "Switch user" one should be able to actually switch the user.

**Comment by clefebvre** [comment]
This is by design, up and down let you navigate through non-hidden users.

I can't reproduce the issue where a user isn't shown.
