### ISSUE TITLE
Circular button session pulldown menu broken

### ISSUE THREAD

**Issue by 4nanook** [linuxmint/slick-greeter#197]
```
 * slick-greeter version (slick-greeter --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
With a large number of desktops installed, the button that gives the pulldown menu with the available desktops can't list them all, thus there is no way to select some.  There is no configuration item to alter the boxsize and fonts they are displayed in to make them all fit, and no scroll of they don't all fit on the same screen.

**Steps to reproduce**
Install gnome, mate, kde, blackbox, cinnamon, and a few others, they won't all show on the menu.

**Expected behaviour**
Expect the menu to scroll, have a way to configure box and font size, or tile, so that any desktop can be chosen.

**Other information**

**Comment by leigh123linux** [comment]
You need to provide the template info next time.

**Comment by 4nanook** [comment]
I don't see how this is pertinent to any of the above since it seems to happen on all platform but it happens on 20.2 Uma with running under qemu emulation when connecting via vnc or rdp, no graphics hardware since it's a virtual machine, same for Debian 11 Bullseye and qemu virtual machine accessing via vnc or rdp, same same for Ubuntu 20.04 in a qemu virtual machine accessing via vnc or rdp, ALL 64 bit.
