### ISSUE TITLE
Feature Request: Nvidia prime switcher

### ISSUE THREAD

**Issue by zeehio** [linuxmint/slick-greeter#20]
[Feel free to close this issue if you feel it is a bad or misplaced idea. If that is the case then receive my deepest apologies, I don't want to waste your time. Thank you for your work on linux mint]

Users of nvidia optimus laptops using "nvidia prime" are required to log-out and log-in every time they want to switch the graphics card. A common scenario is to "boot, log in, run `sudo prime-select nvidia`, log out and log in again". I have to do that whenever I want to use the HDMI output in my laptop.

Having an indicator at the login screen allowing me to switch the graphics card seems logical to me as I would just need to "boot, change graphics card (if I want to) and login".

The tools `/usr/bin/prime-supported` and `/usr/bin/prime-select` can be used to detect if prime is supported and to select the nvidia/intel card, respectively.

Thanks again for your time

**Comment by clefebvre** [comment]
Hi @zeehio, I'd like the input of @tseliot on this.. afaik something needs to happen prior to the greeter's X11 being launched. I could be wrong and I hope I am... because I like your idea.

If you can, please try to implement a prototype to see if this works on optimus.

**Comment by tseliot** [comment]
@clefebvre yes, what you said is correct. I explained how things work in the description here: https://code.launchpad.net/~albertomilone/lightdm/display-stopped-script/+merge/192671
