### ISSUE TITLE
Suggestion: enable "position" parameter in slick-greeter-conf to position login box

### ISSUE THREAD

**Issue by Earthling-Z3R0** [linuxmint/slick-greeter#201]
Please enable "position" parameter in slick-greeter-conf to position login box.

**Comment by Roshanpaudel111** [comment]
yes

**Comment by maloosheck** [comment]
One more kind request for implementing "position" parameter in slick-greeter. Thank you.

**Comment by leigh123linux** [comment]
Duplicate of https://github.com/linuxmint/slick-greeter/issues/92
