### ISSUE TITLE
can I change the "login" window position ???

### ISSUE THREAD

**Issue by 0O000O0** [linuxmint/slick-greeter#205]
```
 * slick-greeter version (slick-greeter --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
can I change the "login" window position ???
how can I put the "login" window right side ???

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by clefebvre** [comment]
No this isn't possible. The layout isn't configurable.
