### ISSUE TITLE
Distro agnostic separation

### ISSUE THREAD

**Issue by fossfreedom** [linuxmint/slick-greeter#22]
Given the distro agnostic aspect of the greeter suggest that Debian folder be moved to a separate branch so that other distros can package without having to patch out that folder.

**Comment by SamBurgos** [comment]
I don't know about any kind of packaging at all, but at least on Arch what I do is to download the tar.xz and (almost) compile it from scratch (actually the package exists on AUR, so I don't do that manually) in my case I didn't have to patch anything to remove or ignore the Debian folder, perhaps some packagers from some other distros can reuse that and automate that process. 

Like I said, I don't know how packaging works on every distro, but maybe guessing a little it should work in that way

**Comment by clefebvre** [comment]
We keep our packaging in the source tree. It doesn't interfere with the build. We were never asked to integrate or host packaging for other distributions but I wouldn't have an issue with that either.
