### ISSUE TITLE
Long session names are cut off

### ISSUE THREAD

**Issue by TheKingOfLight** [linuxmint/slick-greeter#228]
```
 * slick-greeter version 2.0.1
 * Distribution - Arch
 * 64 bit
 ```

**Issue**
In the session selection, the name "Cinnamon on Wayland (Experimental)" is too long and is cut off.
(see picture)
![grafik](https://github.com/linuxmint/slick-greeter/assets/72839891/7a8ffeb6-427f-4052-b0a4-58b4ed21999e)

**Expected behaviour**
The full name of the session should be displayed

**Comment by anaximeno** [comment]
This was fixed recently https://github.com/linuxmint/mint21.3-beta/issues/25
