### ISSUE TITLE
Multi-seat logout/suspend black screen issue with Nvidia

### ISSUE THREAD

**Issue by jamaggs** [linuxmint/slick-greeter#241]
```
 * slick-greeter version (2.0.3)
 * Distribution - (Mint 21.3)
 * Graphics hardware *and* driver used: 
 * GeForce GT 710 Mint default driver = nvidia-driver-470 version 470.239.06-0ubuntu0.22.04.1 and
 * Intel 2nd Generation Core Processor Family Integrated Graphics Controller driver = /lib/modules/5.15.0-107-generic/kernel/drivers/gpu/drm/i915/i915.ko?
 * 64 bit
 ```

**Issue**
I have a multi-seat configuration using loginctl. Seat 0 uses the Nvidia graphics card whilst seat 1 uses the intel onboard graphics. On booting both seats have a login window. However, if I log out from a user on seat 0 then seat 1 goes blank (whether its showing the login screen or whether a user is logged in). I can still log in on seat 1 but can't see what I'm doing. Once logged in the screen functions normally again. The same issue happens on suspend - seat 1 will come out of suspend blank, but I can still log in.

The issue disappears if I use the nouveau drivers.

In addition, in case helpful, the standard lightdm-gtk-greeter has the exact same behavior. Sddm behaves differently, for what it's worth - here logging out from seat 0 makes the seat 1 screen flicker black but it looks like it then automatically restarts the display and it comes back after less than a second - this is much more helpful!

Many thanks for investigating this!

**Steps to reproduce**

Seat up dual seat using loginctl.

Log in with seat 0.

Log out with seat 0.

**Expected behaviour**

Logging out with seat 0 should presumably not affect seat 1. Seat 1 should display login screen (or unlock screen) on resume from suspend.

**Other information**

**Comment by leigh123linux** [comment]
Have you tried this?

https://wiki.debian.org/Multi_Seat_Debian_HOWTO#LightDM

**Comment by jamaggs** [comment]
Hi, just to note that this seemed to resolve itself when I upgraded my kernel from 5.15 to 6.5 so I will mark as closed.
