### ISSUE TITLE
Slick greeter doesn't respect remembered session (invalid session)

### ISSUE THREAD

**Issue by gabrc52** [linuxmint/slick-greeter#27]
Slick greeter doesn't respect the last used or default user session from /home/$USER/.dmrc or lightdm.conf

It thinks all sessions are invalid:

From seat0-greeter.log:
`[+0.47s] DEBUG: slick-greeter.vala:194: Invalid session: 'plasma'. Using session 'xfce' instead.`
`[+0.54s] DEBUG: slick-greeter.vala:194: Invalid session: 'xfce'. Using session 'xfce' instead.`

I'm using the AUR package on Manjaro Linux

**Comment by Ste74** [comment]
Duplicate 
https://github.com/linuxmint/slick-greeter/issues/25
