### ISSUE TITLE
Build failing on FreeBSD (maybe not relevant?)

### ISSUE THREAD

**Issue by janicez** [linuxmint/slick-greeter#3]
I am aware your project is for a Linux distro but I was curious as to how it'd work on freebsd. Build itself passes, but there is a defect in files/Makefile generated by ./configure that means it does not use find . to do find (on FreeBSD, a file argument to find is required; on GNU (which is what LinuxMint is based on), it's not)

**Comment by clefebvre** [comment]
Hi,

Please make a pull request to fix this if you can. We won't be able to test it in FreeBSD, but if you tell us it helps there and it doesn't break anything on our side, we'll be happy to merge it.
