### ISSUE TITLE
slick-greeter v1.0.4 not loading background file

### ISSUE THREAD

**Issue by brysontanner** [linuxmint/slick-greeter#34]
After upgrading to v1.0.4 from v1.0.3, slick greeter no longer renders the greeter background image. The log files that correspond to each version and their differences are found below. The background that should be rendering is found at `/etc/lightdm/background.png`.

v1.0.3 (seat0-greeter.log)
`[+0.00s] DEBUG: settings.vala:159: Overriding dconf setting for draw-grid

[+0.00s] DEBUG: slick-greeter.vala:520: HiDPI support: auto
[+0.07s] DEBUG: slick-greeter.vala:543: Launched at-spi-bus-launcher. PID: 8274
[+0.08s] DEBUG: slick-greeter.vala:552: Starting slick-greeter 1.0.3 UID=108 LANG=en_US.UTF-8
[+0.08s] DEBUG: slick-greeter.vala:555: Setting cursor
[+0.08s] DEBUG: slick-greeter.vala:569: Loading command line options
[+0.08s] DEBUG: slick-greeter.vala:597: Setting GTK+ settings
[+0.13s] DEBUG: slick-greeter.vala:620: Creating Slick Greeter
[+0.13s] DEBUG: slick-greeter.vala:55: Creating background surface
[+0.13s] DEBUG: Connecting to display manager...
[+0.13s] DEBUG: Wrote 22 bytes to daemon
[+0.13s] DEBUG: Read 8 bytes from daemon
[+0.13s] DEBUG: Read 149 bytes from daemon
[+0.13s] DEBUG: Connected version=1.18.3 default-session=plasma show-manual-login=true hide-users=true has-guest-account=false show-remote-login=true
[+0.21s] WARNING: slick-greeter.vala:179: Could not find a default session.
[+0.21s] DEBUG: slick-greeter.vala:197: Using default session: '(null)'
[+0.21s] WARNING: slick-greeter.vala:179: Could not find a default session.
[+0.21s] DEBUG: slick-greeter.vala:197: Using default session: '(null)'
[+0.22s] DEBUG: Loaded session /usr/share/xsessions/default.desktop (Plasma, Plasma by KDE)
[+0.22s] DEBUG: Loaded session /usr/share/xsessions/plasma.desktop (Plasma, Plasma by KDE)
[+0.22s] WARNING: slick-greeter.vala:179: Could not find a default session.
[+0.22s] DEBUG: slick-greeter.vala:197: Using default session: '(null)'
[+0.22s] DEBUG: Starting authentication for user (null)...
[+0.22s] DEBUG: Wrote 16 bytes to daemon
[+0.23s] DEBUG: main-window.vala:198: Screen is 1920x1200 pixels
[+0.23s] DEBUG: main-window.vala:206: Monitor 0 is 1920x1200 pixels at 0,0
[+0.23s] DEBUG: slick-greeter.vala:623: Showing greeter
[+0.23s] DEBUG: slick-greeter.vala:272: Showing main window
[+0.23s] DEBUG: background.vala:488: Regenerating backgrounds
[+0.23s] DEBUG: background.vala:68: Making background /etc/lightdm/background.png at 1920x1200
[+0.23s] DEBUG: slick-greeter.vala:633: Starting main loop
[+0.23s] DEBUG: Read 8 bytes from daemon
[+0.23s] DEBUG: Read 26 bytes from daemon
[+0.23s] DEBUG: Prompt user with 1 message(s)
[+0.23s] WARNING: slick-greeter.vala:179: Could not find a default session.
[+0.23s] DEBUG: slick-greeter.vala:197: Using default session: '(null)'
[+0.24s] WARNING: slick-greeter.vala:179: Could not find a default session.
[+0.24s] DEBUG: slick-greeter.vala:197: Using default session: '(null)'
[+0.25s] DEBUG: slick-greeter.vala:260: starting system-ready sound
[+0.26s] DEBUG: background.vala:121: Render of background /etc/lightdm/background.png complete
[+2.03s] DEBUG: main-window.vala:198: Screen is 1920x1200 pixels
[+2.03s] DEBUG: main-window.vala:206: Monitor 0 is 1920x1200 pixels at 0,0
`

v1.0.4 (seat0-greeter.log)
`[+0.00s] DEBUG: settings.vala:145: Overriding dconf setting for background with /etc/lightdm/background.png

[+0.00s] DEBUG: settings.vala:159: Overriding dconf setting for draw-grid
[+0.00s] DEBUG: slick-greeter.vala:576: HiDPI support: auto
[+0.07s] DEBUG: slick-greeter.vala:599: Launched at-spi-bus-launcher. PID: 11802
[+0.08s] DEBUG: slick-greeter.vala:608: Starting slick-greeter 1.0.4 UID=108 LANG=en_US.UTF-8
[+0.08s] DEBUG: slick-greeter.vala:611: Setting cursor
[+0.08s] DEBUG: slick-greeter.vala:625: Loading command line options
[+0.08s] DEBUG: slick-greeter.vala:653: Setting GTK+ settings
[+0.12s] DEBUG: slick-greeter.vala:676: Creating Slick Greeter
[+0.12s] DEBUG: slick-greeter.vala:55: Creating background surface
[+0.13s] DEBUG: Connecting to display manager...
[+0.13s] DEBUG: Wrote 22 bytes to daemon
[+0.13s] DEBUG: Read 8 bytes from daemon
[+0.13s] DEBUG: Read 149 bytes from daemon
[+0.13s] DEBUG: Connected version=1.18.3 default-session=plasma show-manual-login=true hide-users=true has-guest-account=false show-remote-login=true
[+0.20s] DEBUG: slick-greeter.vala:212: Using default session: 'gnome'
[+0.20s] DEBUG: slick-greeter.vala:212: Using default session: 'gnome'
[+0.20s] DEBUG: main-window.vala:199: Screen is 1920x1200 pixels
[+0.20s] DEBUG: main-window.vala:207: Monitor 0 is 1920x1200 pixels at 0,0
[+0.20s] DEBUG: slick-greeter.vala:679: Showing greeter
[+0.21s] DEBUG: slick-greeter.vala:287: Showing main window
[+0.22s] DEBUG: Loaded session /usr/share/xsessions/default.desktop (Plasma, Plasma by KDE)
[+0.22s] DEBUG: Ignoring session /usr/share/xsessions/gnome.desktop
[+0.22s] DEBUG: Loaded session /usr/share/xsessions/plasma.desktop (Plasma, Plasma by KDE)
[+0.22s] DEBUG: slick-greeter.vala:212: Using default session: 'gnome'
[+0.22s] DEBUG: Starting authentication for user (null)...
[+0.22s] DEBUG: Wrote 16 bytes to daemon
[+0.23s] DEBUG: slick-greeter.vala:689: Starting main loop
[+0.23s] DEBUG: slick-greeter.vala:212: Using default session: 'gnome'
[+0.23s] DEBUG: background.vala:68: Making background #000000 at 1920x1200
[+0.23s] DEBUG: background.vala:79: Render of background #000000 complete
[+0.23s] DEBUG: Read 8 bytes from daemon
[+0.23s] DEBUG: Read 26 bytes from daemon
[+0.23s] DEBUG: Prompt user with 1 message(s)
[+0.23s] DEBUG: slick-greeter.vala:212: Using default session: 'gnome'
[+0.24s] DEBUG: slick-greeter.vala:275: starting system-ready sound
[+2.03s] DEBUG: main-window.vala:199: Screen is 1920x1200 pixels
[+2.03s] DEBUG: main-window.vala:207: Monitor 0 is 1920x1200 pixels at 0,0
`

**Comment by clefebvre** [comment]
Hi,

This should be fixed by https://github.com/linuxmint/slick-greeter/commit/941ecbc5dcb4e7a072c1ca8816d9678f59a96418
