### ISSUE TITLE
A Few Mint-Y Theme Issues with Slick Greeter

### ISSUE THREAD

**Issue by feren** [linuxmint/slick-greeter#43]
When Logo is set to a Logotype image, or something that fits, you'll see that unlike Unity Greeter, the Logo here has no padding AT ALL and literally touches the left of the Slick Greeter area...

(Can't screenshot it as the Logo doesn't appear at all in Test Mode)

**Comment by clefebvre** [comment]
You can use Print Screen as explained in the README.

Also this sounds like a theming issue to me.

**Comment by feren** [comment]
Oh yeah, forgot about PrtScrn...
Let me try it on Mint-Y quickly, was trying it on my Arc fork when I posted this bug...

**Comment by feren** [comment]
Nope, Mint-Y has the same problem, let me try and find the Screenshot Directory...

**Comment by feren** [comment]
@clefebvre Where does Slick place screenshots?

**Comment by feren** [comment]
Another thing I noticed:
After switching from MDM to LightDM Slick Greeter on this installation, I firstly got an error message about something about Logging in via Console makes Switch User work properly, and can't Switch User via gnome-session-quit dialogs, yet Cinnamon's direct Switch User shortcuts work fine...

**Comment by feren** [comment]
*sigh* /var/lib/lightdm is blocked to only Root Access... Is that an upstream issue with LightDM?

**Comment by feren** [comment]
There ya go:
![screenshot](https://user-images.githubusercontent.com/11057934/26893373-029312ac-4bb3-11e7-9e33-6f21068b7812.png)

...and, for reference, the logo itself:
![logo small bg](https://user-images.githubusercontent.com/11057934/26893396-10a3dcf0-4bb3-11e7-93db-4bbcee43fa65.png)

**Comment by JosephMcc** [comment]
You could easily fix this yourself in the image you're using. It's displaying exactly what you provide it. Your logo image has the left side right against the edge. Add a bit of spacing in the logo, problem solved.

**Comment by feren** [comment]
No offense, but I recall that this issue wasn't present in Unity Greeter though, nevermind, I'll try adding some space to the left of the logo image...

**Comment by feren** [comment]
@JosephMcc Just noticed something else, Mint-Y might need to padding fixes for the top panel, it's easier to look at the top of the above screenshot at the icons, than explain what I mean...

**Comment by JosephMcc** [comment]
Mint-Y is already fixed in git master.

**Comment by feren** [comment]
Ok, I'll be waiting the package update for Mint-Y...
