### ISSUE TITLE
guest account accomodations

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/slick-greeter#45]
System: Mint 18.2 beta

There are some aspects in the guest account, which might to get changed or removed, because they do not make any sense or are annoying.

The main annoying thing is the welcome screen. Many of the offered feature (all with package management relation) are not usable for the guest. Further more it is annoying, that the guest has to close at first the information window about the guest account (makes sense) and with a second click the welcome screen.

Also the autostarting update manager does not make any sense in the guest account.

You might also consider to remove the complete administration section from the menu of the guest account. Also this is of no use for the guest account and removing it would make the menu (all applications) more clear.

**Comment by clefebvre** [comment]
Agreed and tracked in the roadmap. These are related to mintupdate and mintwelcome though. There's no need to create an issue for them.
