### ISSUE TITLE
Wrong layout with Logitech wireless keyboards

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/slick-greeter#46]
Logitech keyboard wrong layout, defaults to US with '"' + '@' reversed.

**Comment by clefebvre** [comment]
This should be fixed by https://github.com/linuxmint/slick-greeter/commit/b12098dc07873b965be9497a00cd5d1a6ed05380. Please test if you get a chance.

**Comment by DaveBlack** [comment]
Thank you, I can confirm https://github.com/linuxmint/slick-greeter/commit/b12098dc07873b965be9497a00cd5d1a6ed05380 fixes the issue

**Comment by clefebvre** [comment]
Great, thanks :)
