### ISSUE TITLE
Guest session: Switch user needs to get removed

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/slick-greeter#51]
Mint 18.2 Beta Cinnamon 64 bit.

The switch user function needs to get removed from the guest account, because there is no way to to return to the opened guest session.

Alternatively: Some changes are needed, to allow a guest user to re-enter his session.

Most likely typical scenario: You have allowed a person to open a guest session. During the guest session the owner needs to get quickly int his own account (e. g. for checking his mails). Usually (in case of normal accounts) user switching is just the method to use in this case. But when the owner has finished his task and the guest will continue his session (assume, he was in the middle to search something in the web), he cannot. Trying to re-enter the guest account actually opens a new guest session, the (still opened) old guest session is no more reachable.

So the guest (and also the owner of the pc) must be aware that an interrupted session cannot get re-opened. The guest has to log out and has later to open a new guest session.

**Comment by clefebvre** [comment]
> Alternatively: Some changes are needed, to allow a guest user to re-enter his session.

That would be against LightDM directly, not the greeter.

> there is no way to to return to the opened guest session.

One should be able to use CRL+ALT+Fx and switch the display back to the opened session. I'm assuming the current cinnamon-screensaver doesn't lock guest sessions anymore.
