### ISSUE TITLE
Slick Greeter doesn't respect configuration file. Only uses the gscemas file to set configuration

### ISSUE THREAD

**Issue by SethBarberee** [linuxmint/slick-greeter#52]
I used the sample code on the README to configure slick-greeter by creating `/etc/lightdm/slick-greeter.conf` with this code:

```
[greeter]
background = /var/lib/lightdm/wallpapers/airplane.jpg
draw-user-backgrounds = true
draw-grid = false
show-hostname = true
theme-name = United-Opensuse-Dark
icon-theme = HighContrast
font-name = Overpass Regular 11
xft-antialias = true
xft-hintstyle = hintslight
enable-hidpi = auto

```

However, these settings are not applied. I still get the defaults. Then, I edited and compiled the glib scemas file with these settings and the changes were applied. This seems counter-intuitive to me. The glib file is overwritten each upgrade. The /etc/lightdm/slick-greeter.conf isn't since it is storing the configuration for you.

OS: Arch Linux x86_64
Kernel: 4.11.3-1-ARCH

**Comment by fossfreedom** [comment]
aaahh - the group name is hard-coded as "Greeter" in https://github.com/linuxmint/slick-greeter/blob/master/src/settings.vala - not the usual "greeter" (note the case of G) as per lightdm-gtk-greeter.

simple enough PR to change to lowercase.  More complicated if to change the man page and README to "Greeter".  Happy to-do the PR - just need to know which direction to take.
