### ISSUE TITLE
Slick-greeter does not respect multimonitor setup

### ISSUE THREAD

**Issue by Piiit** [linuxmint/slick-greeter#53]
I have one external monitor above the default laptop monitor, but slick-greeter defaults to have the external one on the right.

**Comment by clefebvre** [comment]
Slick follows the Xorg configuration. If Xorg identifies the right monitor as the default one, then so will Slick.

Note that in your desktop environment, you're only configuring the desktop itself..

**Comment by mtkraai** [comment]
I am having this problem.

I have the following in my Xorg config:
`Section "Monitor"
        Identifier      "eDP1"
EndSection

Section "Monitor"
        Identifier      "HDMI2"
        Option          "Above" "eDP1"
EndSection

Section "InputClass"
        Identifier "evdev touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
        Option "TransformationMatrix" "1 0 0 0 0.5 0.5 0 0 1"
EndSection
`
slick-greeter still arranges the displays left-to-right, but the touchscreen matrix works.  So the touchscreen now controls the bottom half across two screens.

Am I missing something?

**Comment by mtkraai** [comment]
Yup, I was missing something.

I was using my old config file, and monitor identifiers have changed between Ubuntu 14.04 and 18.04: they are now enumerated after a hyphen.  `HDMI1` becomes `HDMI-1`, etc.  Maybe it's a systemd thing.

My working xorg.config:
```
$ cat /etc/X11/xorg.conf.d/91-second-over-touch.conf
# Touchscreen below second monitor.

Section "Monitor"
        Identifier      "eDP-1"
        Option          "PreferredMode" "1920x1080"
        Option          "Position" "0 1080"
EndSection

Section "Monitor"
        Identifier      "HDMI-2"
        Option          "PreferredMode" "1920x1080"
        Option          "Position" "0 0"
EndSection

Section "InputClass"
        Identifier "evdev touchscreen catchall"
        MatchIsTouchscreen "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
        Option "TransformationMatrix" "1 0 0 0 0.5 0.5 0 0 1"
EndSection
```
