### ISSUE TITLE
Blank screen at login screen if the computer is left on it.

### ISSUE THREAD

**Issue by alextpedro** [linuxmint/slick-greeter#59]
If I leave the computer on after it reached the login screen, without actually logging in, the screen eventually goes blank. Moving the mouse or using the keyboard won't get me the screen back, not even typing my password and pressing enter. The only solution is to restart the system and login before the screen goes blank.

I was told to provide proper info and some logging. I don't know which info or which logs so here's my best guess:
inxi -Fz: https://pastebin.com/4cpsQk8M
Auth log: https://pastebin.com/aSwpqwrT

**Comment by clefebvre** [comment]
I don't know why you can't get the display back.. but the key `x.dm.slick-greeter idle-timeout` is set to 300 seconds by default. If you set it to 0, it should disable the blanking.

We'll add this to lightdm-settings so it can be configured graphically.

**Comment by alextpedro** [comment]
I don't know what happened but after the last round of updates I've been unable to reproduce this issue. Seems like it might not have actually been lightdm's fault.

**Comment by clefebvre** [comment]
I checked on my side also, and idle-timeout is obsolete.
