### ISSUE TITLE
lock-screen pops up briefly when switching user

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/slick-greeter#60]
I'm not sure where the right place for this issue is, also it might be a problem limited to Arch/Manjaro. Anyway, what I see is this:
I launch the greeter with "Switch user", then log back into the existing session.
Now I see the open session just briefly, but then for a moment the lock-screen pops up and disappears again. After that everything is fine with the session.
Any ideas?

**Comment by clefebvre** [comment]
Closing this for now as no issue was identified. Please use support channels to troubleshoot and come back to us if a bug is found.
