### ISSUE TITLE
Guestaccount in upgraded system has full access to user accounts

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/slick-greeter#63]
Linux Mint 18.2 Cinnamon 64 bit, upgraded from 18.1 following [these](http://blog.linuxmint.com/?p=3306) instructions. Next installed LightDM and removed MDM following the same instructions.

If I go into the guest account I have unlimited access to all installed user accounts and their content.
I can access the accounts as well via Nemo (simply clicking file system in the side bar -> home -> account name) or via terminal (cd /home/account_name).

In a fresh install this problem does not exist.

For now it should be said in the blog about upgrading, that the guest account does in this case not give the same privacy protection as in a new install. The current warning ("not recommended for novice users") does not give a hint about the problem.

**Comment by Cos-mo** [comment]
Possibly somehow related to [url=https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/1663157]this[/url] bug?

At least the command cat /proc/self/attr/current produces in an upgraded system "uncorfirmed" as result, whereas in a new install of Mint 18.2 it gives "/usr/lib/lightdm/lightdm-guest-session (enforce)".

It is a serious security leak for local attacks!

**Comment by Pjotr123** [comment]
Maybe this could be a temporary workaround, until there's a fix? In all of the other accounts:
chmod -v 700 $HOME

**Comment by Cos-mo** [comment]
After some struggling around it came up, that in an upgraded 18.2 the package apparmor is missing. In a fresh install it exists in the system.

Bug in the upgrade mechanism of the update manager?

**Comment by Pjotr123** [comment]
It's not a bug in the upgrade mechanism, because that doesn't install LightDM in the first place.... It's apparently an omission in the how-to in the blog, for installing LightDM *after* the upgrade.

This is the current how-to:
apt install slick-greeter lightdm-settings

Apparently it should be:
apt install slick-greeter lightdm-settings apparmor

**Comment by Cos-mo** [comment]
The instructions have been corrected. So I close this.
