### ISSUE TITLE
Will only use the smaller size of a Multimonitor system with different screen sizes

### ISSUE THREAD

**Issue by nd4c** [linuxmint/slick-greeter#66]
```
 * slick-greeter version (slick-greeter --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```
$ inxi -GS
System:    Host: mintyfresh Kernel: 4.8.0-58-generic x86_64 (64 bit) Desktop: Cinnamon 3.4.3
           Distro: Linux Mint 18.2 Sonya
Graphics:  Card: Intel Sky Lake Integrated Graphics
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1440x900@59.89hz, 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2) GLX Version: 3.0 Mesa 12.0.6
$ slick-greeter -v
[+0.00s] DEBUG: settings.vala:145: Overriding dconf setting for background with /usr/share/backgrounds/linuxmint/edesigner_linuxmint.png
[+0.00s] DEBUG: settings.vala:145: Overriding dconf setting for enable-hidpi with auto
[+0.00s] DEBUG: settings.vala:159: Overriding dconf setting for draw-user-backgrounds
[+0.00s] DEBUG: settings.vala:159: Overriding dconf setting for draw-grid
[+0.00s] DEBUG: slick-greeter.vala:587: HiDPI support: auto
[+0.13s] DEBUG: slick-greeter.vala:613: Launched at-spi-bus-launcher. PID: 4393
[+0.18s] DEBUG: slick-greeter.vala:622: Starting slick-greeter 1.0.7 UID=1000 LANG=en_US.UTF-8
[+0.18s] DEBUG: slick-greeter.vala:625: Setting cursor
[+0.18s] DEBUG: slick-greeter.vala:639: Loading command line options
slick-greeter 1.0.7

**Issue**
Slick-Greeter will use the lower resolution (1440x900) for both screens.  I do not know how to change this in the settings, or if I should even need to.  I would expect the default behaviour to be the "Expected behaviour" listed below.

**Steps to reproduce**
reboot or logout.  I could not find any settings that effected corrected it.

**Expected behaviour**
Expected the screen with 1920x1080 resolution to display using 1920x1080 resolution and the screen with 1440x900 resolution to display using 1440x900.  

**Other information**
This is on a Mint Cinnamon system that was upgraded from 18.1 to 18.2 and I converted from MDM (default for 18.1) to Slick-greeter (default for 18.2), MDM would use the correct resolutions.

**Comment by clefebvre** [comment]
Is this specific to slick greeter or lightdm? Can you reproduce the issue with lightdm-gtk-greeter for instance?

**Comment by nd4c** [comment]
lightdm-gtk-greeter does the reverse.  It uses the largest resolution for both screens, so that the smaller screen is now messed up.  

There is also a difference in how they hand off the displays after logging in.  slick greeter will have the screen go blank for a sort of long time and then the desktop displays.  gtk greeter, on the other hand, does not blank out the screen, and you see a messed up desktop and it trying to change the resolutions to match both windows.  Finally it settles down and the desk top looks normal.

**Comment by nd4c** [comment]
Another not about the lightdm greeters.  Both are apparently just duplicating the screen on both monitors. As I type in the password, either greeter will show me typing it in on both monitors.

**Comment by nd4c** [comment]
lightdm-gtk-greeter has had this problem since 2014.  In 2017 Ubuntu confirmed the bug:
https://bugs.launchpad.net/lightdm-gtk-greeter/+bug/1314603

**Comment by clefebvre** [comment]
> Both are apparently just duplicating the screen on both monitors.

That's weird... it should show the background on both monitors, but the password box and user list should only be visible on the monitor where your mouse cursor is.

You've got a mouse cursor on each monitor?

Maybe you're mirrored at Xorg.conf level?

**Comment by clefebvre** [comment]
Check /var/log/lightdm/seat0-greeter.log.

Here's mine with dual monitors... everything works fine here:

```
[+0.23s] DEBUG: main-window.vala:205: Screen is 4480x1440 pixels
[+0.23s] DEBUG: main-window.vala:213: Monitor 0 is 1920x1200 pixels at 0,0
[+0.23s] DEBUG: main-window.vala:213: Monitor 1 is 2560x1440 pixels at 1920,0
[+0.23s] DEBUG: slick-greeter.vala:677: Showing greeter
[+0.23s] DEBUG: slick-greeter.vala:291: Showing main window
```
And

```
[+0.25s] DEBUG: background.vala:68: Making background /usr/share/backgrounds/linuxmint-sonya/jenemark_conifer_cone.jpg at 1920x1200,2560x1440
[+0.38s] DEBUG: background.vala:121: Render of background /usr/share/backgrounds/linuxmint-sonya/jenemark_conifer_cone.jpg complete
```

**Comment by nd4c** [comment]
@clefebvre 

In answer to the mouse cursor question.  Yes, the mouse cursor is on both monitors - exact duplicate screens.  You mentioned being mirrored at the Xorg.level.  Not sure how to change that, especially for just the login screen.  Once I'm logged in the monitors work fine as expected.

For the post about the log, the computer in question is my home desktop and I'm not at home.  Will check when I can.

**Comment by clefebvre** [comment]
Ok, if your mouse cursor is on both screens, you're definitely mirrored.

The display settings you manipulate in your sessions, only apply to your DE. The DM itself follows your Xorg configuration.
