### ISSUE TITLE
slick-greeter hang on boot, after autoremove removes mdm config

### ISSUE THREAD

**Issue by ghost** [linuxmint/slick-greeter#67]
```
 * slick-greeter version: 1.0.7.
 * Distribution: Mint 18.2.
 * Graphics hardware *and* driver used: Intel, but details irrelevant I think.
 * 64 bit.
 ```

**Issue**

Slick-greeter hangs on boot.

**Steps to reproduce**

1. Install Mint 18.2. (I upgraded from 18.1. That may or not be relevant.)
2. Install the new greeter as per published instructions.
3. Reboot. (I reused the system for some weeks before taking the next step.)
4. `sudo apt autoremove` and accede when when asked whether you want to removed mdm config.
5. Reboot.

**Expected behaviour**

**Other information**

I fixed the problem thusly: `sudo dpkg-reconfigure mdm`

**Comment by smurphos** [comment]
An alternative fix is `sudo dpkg-reconfigure lightdm`

**Comment by icarter09** [comment]
Closing this issue since...
 1. The submitter is no longer present on github.
 2. @smurphos provided a work around.

**Comment by smurphos** [comment]
@icarter09 @clefebvre 

Hi,

it would be helpful if Clem updated the instructions on how to switch from MDM to LightDM here https://blog.linuxmint.com/?p=3306 to amend them to be

```
apt install slick-greeter lightdm lightdm-settings apparmor
Select LightDM as default when asked
apt purge --autoremove mdm
sudo dpkg-reconfigure lightdm
sudo reboot
```

Users to this day occasionally report this issue on the forums when trying to switch to lightdm from mdm on 18.x installs. Using the above instructions avoids the issue entirely.
