### ISSUE TITLE
Enchancement: intelligent pre-selection of user-to-log-into

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/slick-greeter#69]
```
 * slick-greeter version: 1.0.7
 * Distribution - Mint 18.2
 * 64 bit
 ```

**Issue**

Consider the following series of circumstances.

1. I switch from user A to B.
2. From user B's session, I initiate the fast-user switching function (for a second time) or log out.
3. The greeter has a user pre-selected for login, namely, B, i.e., _the account from which I have just  logged out or (as the case may be) switched away from_.

**Steps to reproduce**

Follow the series of actions described above.

**Expected behaviour**

It would be better, when there are two user accounts, to offer for login _the account that the user has not just left_. With >2 user accounts, things get a little more complex, but, again, there's little point offering the account that just's been exited/suspended.

**Other information**

**Comment by clefebvre** [comment]
Many thanks for contributing. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
