### ISSUE TITLE
Some settings not respected

### ISSUE THREAD

**Issue by gabrc52** [linuxmint/slick-greeter#74]
```
 * slick-greeter 1.0.8
 * Distribution - Manjaro Linux
 * 64 bit
 ```

**Issue**

At least the following settings are not respected:
`show-a11y=false` (set as true)
`show-keyboard=false` (set as true)
`font-name=customfontname` (set as Ubuntu or DejaVu Sans except for top bar) (reported in #50)

**Steps to reproduce**

Set these settings in /etc/lightdm/slick-greeter.conf

**Expected behaviour**

Slick greeter respects them

**Comment by nstommel** [comment]
I second this, the greeter looks really inconsistent. Why hardcode fonts?!

**Comment by JosephMcc** [comment]
I assume it was inherited from Ubuntu this way. Could probably be improved and I'd assume PR's would be welcome. Probably just no one has gotten to it yet.

**Comment by clefebvre** [comment]
show-keyboard and show-a11y work fine here. This is 2023 so I assume it got fixed on master since 2017 :)

Regarding fonts, we've got #50 already so closing this one.
