### ISSUE TITLE
Slick Greeter don't use the /etc/lightdm/slick-greeter.conf

### ISSUE THREAD

**Issue by hamdyaea** [linuxmint/slick-greeter#80]
Slick-greeter : 1.0.8
Distribution - Debian Buster AMD64

Issue

I added the slick-greeter.conf file and configured the backgroung, logo etc.
After a reboot or a logout slick-greeter is remplacing the lightdm-greeter but I can't see my background image and logo or any change. My images files are in /usr/share/wallpaper/

**Comment by leigh123linux** [comment]
Post

```
lightdm --show-config
```

**Comment by qnarkill** [comment]
Did this ever get solved and how?

**Comment by vinzv** [comment]
Don't think so, the whole configuration is a huge mess:
Some of the settings in /etc/lightdm/slick-greeter.conf are only respected if there's a space before and after the = sign. Which is even more ridiculous as the official documentation only lists parameters without this space sign.

**Comment by qnarkill** [comment]
Im in 17.10 and the slick-greeter 1.0.8-2 seems to use system wallpaper instead of wallpaper instead of i have in the .conf file. If i have variety changing wallpapers then it changes to black.

**Comment by oberon2007** [comment]
I've just removed my config file and had a new one created by using **lightdm-settings** GUI. Still the background is the one I have selected for cinnamon desktop, not the one specified in the config.

**Comment by oberon2007** [comment]
```
$ lightdm --show-config
   [LightDM]
A  run-directory=/run/lightdm

   [Seat:*]
A  greeter-session=lightdm-slick-greeter
A  user-session=cinnamon
A  session-wrapper=/etc/lightdm/Xsession

   [VNCServer]
A  user-session=cinnamon
A  session-wrapper=/etc/lightdm/Xsession

Sources:
A  /etc/lightdm/lightdm.conf
```

**Comment by Ste74** [comment]
Have you tryto use the gsettings ?

**Comment by oberon2007** [comment]
That doesn't have any effect either.

**Comment by oberon2007** [comment]
```
gsettings get x.dm.slick-greeter background
"'file:///usr/share/backgrounds/adapta.jpg'"
```
But that's not the one I see.

**Comment by Ste74** [comment]
Adapta background is your choice ?

**Comment by oberon2007** [comment]
Looks like this issue is specific to the cinnamon desktop.
@Ste74 says that settings the bakground is still working normally with Mate and the maintainer of our Openbox edition doesn't seem to experience these problems, either...

**Comment by mbirth** [comment]
I had the same problem with slick-greeter in xUbuntu. The trick was to change the settings group from `greeter` to `Greeter`. Also I'm not sure if `draw-user-backgrounds = false` was needed. But it works now for me.

**Comment by oberon2007** [comment]
Well, my **slick-greeter.conf** already looks like this:
```
[Greeter]
background=/usr/share/backgrounds/MJR-tiles.jpg
draw-grid=false
theme-name=Adapta-Nokto-Eta-Maia
icon-theme-name=Papirus-Adapta-Maia
```
This is how **lightdm-settings** creates the file :wink:

**Comment by mbirth** [comment]
Mine looks like this:

```
[Greeter]
background = /usr/share/wallpapers/greybird.svg
draw-user-backgrounds = false
```

And that works. You might also try to manually add spaces before and after the `=`s.

**Comment by SirSharanChakradhar** [comment]
Still dont work, I use Archlabs with slick-greeter

**Comment by leovp** [comment]
@SirSharanChakradhar does `lightdm` group have read access to the background file?

**Comment by SirSharanChakradhar** [comment]
@leovp Yes.

**Comment by MintDja** [comment]
Linuxmint начиная наверно с версии 18.2 ... 18.3 точно присутствует. Вобщем когда вместо mdm решили поставить это недоразумение lightdm. Вобщем суть. При удаленной сессии по vnc если залочить экран, то получится черное окно. При этом теряется насколько помню управление даже мышью, может мышь и ездит, но ничего не видно, просто черный экран. Поэтому и невозможно ничего сделать. Опять же при использовании Anydesk если залочить экран, то так же нет возможности ни ввести пароль, ни закрыть окно. Приходится сессию тушить. Данный момент был решен установкой xscreensaver. Но полагаю по vnc при рестарте системы проблема никуда не делась.

**Comment by vibowit** [comment]
> @SirSharanChakradhar does `lightdm` group have read access to the background file?

For me, moving the background file from my home directory to /usr/share/slick-greeter did the trick.

**Comment by hesxenon** [comment]
so, just because none of the solutions here or elsewhere worked for me I'm adding my findings to this thread. I noticed that when I tried to `su - lightdm` the lightdm account was expired. `chage -E -1 lightdm` fixed it for me

**Comment by jmvalenciz** [comment]
I just had to change `[Greeter]` to `[greeter]`

**Comment by icarter09** [comment]
After reading through the comments, it looks like most people have had the issue resolved. Closing this ticket out. If anyone feels this is still an issue or is still experiencing the issue, please let me know and I'll reopen the ticket. Thanks.
