### ISSUE TITLE
Not Mirroring

### ISSUE THREAD

**Issue by Immortalin** [linuxmint/slick-greeter#82]
```
 * Distribution - Ubuntu Budgie 17.10
 * Graphics hardware: Dual Intel and Nvidia Graphics. Only intel driver in use
 * 64 bit
 ```

**Issue**
Login prompt is not being mirrored. Default behaviour on most DMs is to mirror display when second monitor is connected

**Steps to reproduce**
Plug in external display, reboot and login

**Expected behaviour**
Login screen mirrored not extended

**Other Infomation**
On X11

**Comment by tristan957** [comment]
I have a dock, so I normally keep my lid closed when turning on my computer. I wonder if our issues are related. Slick seems to think my closed laptop lid is still the main screen when it's not even on. @devs please let me know if you would like me to file a separate issue.

**Comment by icarter09** [comment]
@Immortalin  are you still experiencing this issue?

**Comment by Immortalin** [comment]
I don't have an external display to test so I am closing it for now.
