### ISSUE TITLE
No un-hide shortcut given

### ISSUE THREAD

**Issue by cromefire** [linuxmint/slick-greeter#83]
* slick-greeter version: 1.0.8
 * Distribution: Ubuntu MATE 17.10 Shipped by default
 * Graphics: not important for this issue
 * 64 bit

**Issue**
The shortcut for un-hiding hidden users is undocumented

**Steps to reproduce**
Hide some user and try to un-hide it with a shortcut

**Expected behaviour**
It says something like: "until Alt + xy is hit" 

**Current status**
It says: "until a special key combination is hit"

**Comment by mojojoseph** [comment]
Precisely.  What exactly is the special key combination?

**Comment by demling** [comment]
If I read [this part of the code](https://github.com/linuxmint/slick-greeter/blob/3163bc67145db653ee39a78373541a2894e6af78/src/main-window.vala#L359) correctly the key combination is Ctrl+Alt+Shift.

**Comment by icarter09** [comment]
@cromefire  are you still experiencing this issue?

**Comment by cromefire** [comment]
I'll check later, I'm running Ubuntu 18.04 though, so it's probably not the latest version

**Comment by cromefire** [comment]
`Ctrl+Alt+Shift` didn't work
