### ISSUE TITLE
I'm only able to see the first 6 desktop sessions

### ISSUE THREAD

**Issue by SolarAquarion** [linuxmint/slick-greeter#85]
```
 * slick-greeter version (slick-greeter --version)

1.12
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)

Arch
 * Graphics hardware *and* driver used

Nvidia and Intel, Nouveau
 * 32 or 64 bit

64bit
 ```

**Issue**
I'm only able to see the first 6 desktop sessions

**Steps to reproduce**
Have a laptop open the session chooser and have more then 6 sessions installed

**Expected behaviour**
Being able to scroll up and down all the desktop sessions

**Comment by Vahan86** [comment]
@SolarAquarion, is this still an issue with slick-greeter 1.3.2?

**Comment by SolarAquarion** [comment]
I still can't scroll down and see all the sessions I have installed

**Comment by Vahan86** [comment]
@SolarAquarion, thanks for the update.
@icarter09, can we mark this issue as a bug?

**Comment by SolarAquarion** [comment]
huh, it seems that it doesn't work properly with xephyr debug mode either on my desktop

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/slick-greeter/commit/1480b029099ea24724d307943dc742a42fcd3159
