### ISSUE TITLE
Feature Request: Manual/Standard/Simple login

### ISSUE THREAD

**Issue by moocan** [linuxmint/slick-greeter#97]
Hello,

Is there any way to have a manual or standard simple login.
I mean is it possible to have just two empty fields, one for the user name and one for the password without the list of all users ?

Something like with the Unity Greeter ?
greeter-hide-users=true
greeter-show-manual-login=true

Kind Regards

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
There is a setting in lightdm-settings to do this.
